# Generated by Django 4.0.6 on 2022-07-29 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name Product')),
                ('rating_ms', models.IntegerField(default=0, verbose_name='Rating MS')),
                ('now_on_sale', models.BooleanField(default=False, verbose_name='Now on Sale')),
                ('rating_gavimo', models.IntegerField(default=0, verbose_name='Rating Gavimo')),
                ('rating_eneba', models.IntegerField(default=0, verbose_name='Rating Eneba')),
                ('total_rating', models.IntegerField(default=0, verbose_name='Total Rating')),
                ('game_sale', models.BooleanField(default=False, verbose_name='Game Sale')),
                ('date_end_sale', models.DateTimeField(default=datetime.datetime(2022, 7, 29, 19, 33, 43, 20883), verbose_name='Date End Sale')),
                ('first_price', models.FloatField(default=0, verbose_name='First Price')),
                ('first_region', models.CharField(max_length=100, verbose_name='First Region')),
                ('second_price', models.FloatField(default=0, verbose_name='Second Price')),
                ('second_region', models.CharField(max_length=100, verbose_name='Second Region')),
                ('difference', models.FloatField(default=0, verbose_name='Difference')),
                ('buy', models.BooleanField(default=False, verbose_name='BUY')),
            ],
        ),
    ]
